# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=255)),
                ('price', models.IntegerField(verbose_name='price')),
                ('master', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='psb.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacantTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacant_date_time', models.DateTimeField(verbose_name='datetime')),
                ('procedure', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='psb.Procedure')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='vacant_time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='psb.VacantTimes'),
        ),
    ]
